Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  # give our VM an ip address we can access from our browserq
  config.vm.network "private_network", ip: "192.168.14.14"

  config.vm.provision "ansible" do |ansible|
    ansible.sudo = true
    ansible.playbook = "provisioning/playbook.yml"
  end
end

