---
- name: Download node.js binary tarball
  get_url: url=https://nodejs.org/dist/v6.0.0/node-v6.0.0-linux-x64.tar.gz dest=/home/vagrant force=yes
  tags: nodejs

- name: Unarchive node.js tarball
  unarchive: src=/home/vagrant/node-v6.0.0-linux-x64.tar.gz dest=/usr/local copy=no
  tags: nodejs

- name: Add /usr/local symlink to unarchived tarball
  file: src=/usr/local/node-v6.0.0-linux-x64 dest=/usr/local/node state=link
  tags: nodejs

- name: Add ~/.profile with updated node path
  template: src=profile dest=/home/vagrant/.profile
  tags: nodejs
